### PR TITLE
break when value is undefined for page type

### PR DESCRIPTION
**Pull request by omonk**
Taking over this PR - https://github.com/askorama/orama/pull/726

### CODE REVIEW

**Comment by micheleriva** [comment]
@raiindev can you please help reviewing this?

**Comment by raiindev** [comment]
@omonk how can i replicate the scenario?

**Comment by omonk** [comment]
@raiindev on a fresh install of docusaurus, turn the blog off:

```
presets: [
    [
      "classic",
      {
        // other config
        blog: false,
      } satisfies Preset.Options,
    ],
  ],
```

Add Orama plugin, run build, see the build fails. 

The changes in this PR are the same as https://github.com/askorama/orama/pull/726 which was approved by @micheleriva  - CI failed because the contributor changed a bunch of package.json values

**Review by raiindev — APPROVED** [review]
LGTM

**Comment by Phil-Sime** [comment]
> @raiindev on a fresh install of docusaurus, turn the blog off:
> 
> ```
> presets: [
>     [
>       "classic",
>       {
>         // other config
>         blog: false,
>       } satisfies Preset.Options,
>     ],
>   ],
> ```
> 
> Add Orama plugin, run build, see the build fails.
> 
> The changes in this PR are the same as #726 which was approved by @micheleriva - CI failed because the contributor changed a bunch of package.json values

I made a single line change. I didn't "change a bunch of package.json values".  https://github.com/askorama/orama/pull/726/commits/deb4c50c21d1a4c50d6737daf71f00ecd47df635

**Comment by omonk** [comment]
@Phil-Sime see your PR, there are 16k LOC. this is due to changes in package.json which you committed to your branch. This is why CI was failing and the maintainers requested you to take another look

**Comment by omonk** [comment]
@Phil-Sime my apologies, I've just looked at the commits on the pr and can see there are two other commits from a different author which changed the package.json

**Pull request merged**
